version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - Verbalinsurection
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - Verbalinsurection
  ignore:
  - dependency-name: python
    versions:
    - 3.9.3
