{
 "title": "Covid France",
 "time": { "from": "2020-03-22T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Departement",
    "query": "SHOW TAG VALUES ON \"covidfr\" WITH KEY = \"dep\""
   }
  ]
 },
 "panels": [
  {
   "title": "Hospitalisations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT last(\"hosp\") as \"hosp\", \"longitude\", \"latitude\", \"dep\" FROM \"Covid_France\" GROUP BY \"dep\"",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Réanimations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT last(\"rea\") as \"rea\", \"longitude\", \"latitude\", \"dep\" FROM \"Covid_France\" GROUP BY \"dep\"",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Décès",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT last(\"dc\") as \"dc\", \"longitude\", \"latitude\", \"dep\" FROM \"Covid_France\" GROUP BY \"dep\"",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Global hospitalisations",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dep" ], "type": "tag" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT sum(last) FROM (SELECT last(\"hosp\") FROM \"Covid_France\" GROUP BY \"dep\")",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Global réanimations",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dep" ], "type": "tag" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT sum(last) FROM (SELECT last(\"rea\") FROM \"Covid_France\" GROUP BY \"dep\")",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Global décès",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dep" ], "type": "tag" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT sum(last) FROM (SELECT last(\"dc\") FROM \"Covid_France\" GROUP BY \"dep\")",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hospitalisations",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dep" ], "type": "tag" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT sum(last) FROM (SELECT last(\"hosp\") FROM \"Covid_France\" WHERE \"dep\" =~ /^$dep$/ GROUP BY \"dep\")",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    }
   ]
  },
  {
   "title": "Réanimations",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dep" ], "type": "tag" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT sum(last) FROM (SELECT last(\"rea\") FROM \"Covid_France\" GROUP BY \"dep\")",
     "select": [
      [
       { "params": [ "rea" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    }
   ]
  },
  {
   "title": "Décès",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dep" ], "type": "tag" }
     ],
     "measurement": "Covid_France",
     "query": "SELECT sum(last) FROM (SELECT last(\"dc\") FROM \"Covid_France\" GROUP BY \"dep\")",
     "select": [
      [
       { "params": [ "dc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    }
   ]
  },
  {
   "title": "Vue globale",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dep" ], "type": "tag" }
     ],
     "measurement": "Covid_France",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Hospitalisations" ], "type": "alias" }
      ],
      [
       { "params": [ "rea" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Réanimations" ], "type": "alias" }
      ],
      [
       { "params": [ "dc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Décès" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Hospitalisations",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    },
    {
     "alias": "Réanimations",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "select": [
      [
       { "params": [ "rea" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    },
    {
     "alias": "Décès",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "select": [
      [
       { "params": [ "dc" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    }
   ]
  },
  {
   "title": "Delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Hospitalisations",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "select": [
      [
       { "params": [ "hosp" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    },
    {
     "alias": "Réanimations",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "select": [
      [
       { "params": [ "rea" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    },
    {
     "alias": "Décès",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Covid_France",
     "select": [
      [
       { "params": [ "dc" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "dep", "operator": "=~", "value": "/^$Departement$/" }
     ]
    }
   ]
  }
 ]
}